#!/bin/sh
PKG_VERSION=$(node -p "JSON.parse(require('fs').readFileSync('package.json','utf8')).version")
EXPECTED_TAG="v$PKG_VERSION"

while read local_ref local_sha remote_ref remote_sha; do
  case "$local_ref" in
    refs/tags/*)
      TAG="${local_ref#refs/tags/}"
      if [ "$TAG" != "$EXPECTED_TAG" ]; then
        echo "Error: tag \"$TAG\" does not match package.json version \"$EXPECTED_TAG\""
        exit 1
      fi
      ;;
  esac
done
